modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/moist-mason/${mod_id}"
authors="moist-mason"

description='''
Library mod for registries, data generators, and other boilerplate modding stuff.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"